### ISSUE TITLE
Crashing on hot reload with gatsby develop

### ISSUE THREAD

**Issue by JaKXz** [gatsbymanor/gatsby-theme-massively#3]
This crash only occurs on hot reload, but if I manually reload the page everything loads fine.

<img width="1032" alt="screen shot 2018-03-27 at 2 04 53 pm" src="https://user-images.githubusercontent.com/2642545/37985836-dc49cb6c-31c7-11e8-8a5c-4c7320f679db.png">

**Comment by JaKXz** [comment]
This issue also occurs when clicking the downward arrow that sets the hash path to `#header`.

I found a fix by changing line 53 in `layouts/index.js` to:

```js
const {pathname} = nextProps.location
```

but I'm curious if this is the correct solution and the bug is indeed just a typo?

**Comment by nodox** [comment]
Interesting observation. What is `jay` version are you running? 

```
$ jay --version
```

**Comment by JaKXz** [comment]
```
$ jay --version
0.3.3
```

and, in case it's helpful:

```
$ cat jay.json
{
  "theme": {
    "name": "massively",
    "version": "^0.2.0"
  }
}
```

**Comment by nodox** [comment]
After rereading your error message your fix is the solution. I rewrote that theme yesterday in order to push a new `jay` release, namely everything related to props. 😅.

Make the change locally for you project. Open a PR and I will merge it. 

Right now`jay` does not have a have to update to the latest patch on a theme.  If you now how to do that it would be another useful PR. 😄
